api/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from questions import api_views as questions
from users import api_views as users


router = SimpleRouter()
router.register(r'questions', questions.QuestionList,
                basename="questions_list")
router.register(r'submit', questions.SubmissionViewSet, basename="submit")
router.register(r'hospitals', users.HospitalChoices, basename="hospitals")


urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('get-token/', questions.CustomAuthToken.as_view(), name='get_token'),
    path('register/', users.Register.as_view(), name='register'),
    path('', include(router.urls)),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('portal/', include('portal.urls')),
]

portal/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *


app_name='portal'

urlpatterns = [
    path('', index_view, name='dashboard'),
    path('today/', reports_today_view, name='reports_today'),
    path('archive/', reports_archive_view, name='archive'),

    path('all_patients/', all_patients_view, name='all_patients'),
    path('all_patients/<int:pk>', patient_detail_view, name='patient_detail'),
    path('add_patient/', patient_add_view, name='patient_add'),

    path('assign/', assign_view, name='assign'),
    path('assign/<int:pk>/', assign_patient_view, name='assign_patient'),

    path('all_doctors/', all_doctors_view, name='all_doctors'),
    path('all_doctors/<int:pk>/', doctor_detail_view, name='doctor_detail'),
    path('add_doctor/', doctor_add_view, name='doctor_add'),
    
    path('reports/<int:pk>/', report_detail_view, name='report_detail'),

    path('login/', LoginView.as_view(template_name="portal/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name="portal/logout.html"), name='logout'),
]

portal/models.py
from django.db import models

# Create your models here.

portal/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from datetime import date
import math
from users.models import Profile
from users.forms import DoctorProfileForm, AssignForm
from questions.models import Submission


# TODO: refactor to clean up repeated code

@login_required
def index_view(request):
    # reduce number of db reads:
    profiles = Profile.objects.filter(hospital_name=request.user.username)
    submissions = Submission.objects.filter(
        user__profile__hospital_name=request.user.username)

    counts = {
        'patients': profiles.filter(user_type='patient').count(),
        'status_updates': submissions.filter(date_added__startswith=date.today()).count(),
        'doctors': profiles.filter(user_type='doctor').count(),
        'severe': len([elem for elem in submissions.filter(date_added__startswith=date.today()) if elem.data['How is your condition (Mild/ Moderate/ Severe) in your understanding'].lower() == 'severe'])
    }

    SUB_DISPLAY = 10
    sub_start = int(request.GET.get('start')) if 'start' in request.GET else 0
    sub_end = int(request.GET.get('end')
                  ) if 'end' in request.GET else SUB_DISPLAY
    sub_total = submissions.count()
    sub_pages = math.ceil(sub_total / SUB_DISPLAY)
    current_page = math.ceil(sub_end / SUB_DISPLAY)

    submissions = submissions.order_by('-date_added')[sub_start:sub_end]

    context = {
        'page': 'dashboard',
        'counts': counts,
        'submissions': submissions,
        'sub_start': sub_start + 1,
        'sub_end': sub_end if sub_end < sub_total else sub_total,
        'sub_pages': sub_pages,
        'sub_total': sub_total,
        'sub_range': range(1, sub_pages + 1),
        'current_page': current_page
    }
    return render(request, 'portal/index.html', context)


@login_required
def reports_today_view(request):

    profiles = Profile.objects.filter(hospital_name=request.user.username)
    submissions = Submission.objects.filter(
        user__profile__hospital_name=request.user.username)

    counts = {
        'new_patients': profiles.filter(user__date_joined__startswith=date.today()).count(),
        'status_updates': submissions.filter(date_added__startswith=date.today()).count(),
        'severe': len([elem for elem in submissions.filter(date_added__startswith=date.today()) if elem.data['How is your condition (Mild/ Moderate/ Severe) in your understanding'].lower() == 'severe'])
    }

    SUB_DISPLAY = 25
    sub_start = int(request.GET.get('start')) if 'start' in request.GET else 0
    sub_end = int(request.GET.get('end')
                  ) if 'end' in request.GET else SUB_DISPLAY
    sub_total = submissions.all().count()
    sub_pages = math.ceil(sub_total / SUB_DISPLAY)
    current_page = math.ceil(sub_end / SUB_DISPLAY)

    submissions = submissions.order_by('-date_added')[sub_start:sub_end]

    context = {
        'page': 'today',
        'counts': counts,
        'submissions': submissions,
        'sub_start': sub_start + 1,
        'sub_end': sub_end if sub_end < sub_total else sub_total,
        'sub_pages': sub_pages,
        'sub_total': sub_total,
        'sub_range': range(1, sub_pages + 1),
        'current_page': current_page
    }
    return render(request, 'portal/reports_today.html', context)


@login_required
def reports_archive_view(request):

    profiles = Profile.objects.filter(hospital_name=request.user.username)
    submissions = Submission.objects.filter(
        user__profile__hospital_name=request.user.username)

    counts = {
        'total': profiles.count(),
        'patients': profiles.filter(user_type='patient').count(),
        'status_updates': submissions.all().count(),
        'doctors': profiles.filter(user_type='doctor').count(),
    }

    SUB_DISPLAY = 50
    sub_start = int(request.GET.get('start')) if 'start' in request.GET else 0
    sub_end = int(request.GET.get('end')
                  ) if 'end' in request.GET else SUB_DISPLAY
    sub_total = submissions.all().count()
    sub_pages = math.ceil(sub_total / SUB_DISPLAY)
    current_page = math.ceil(sub_end / SUB_DISPLAY)

    submissions = submissions.order_by('-date_added')[sub_start:sub_end]

    context = {
        'page': 'archive',
        'counts': counts,
        'submissions': submissions,
        'sub_start': sub_start + 1,
        'sub_end': sub_end if sub_end < sub_total else sub_total,
        'sub_pages': sub_pages,
        'sub_total': sub_total,
        'sub_range': range(1, sub_pages + 1),
        'current_page': current_page
    }
    return render(request, 'portal/reports_archive.html', context)


@login_required
def all_patients_view(request):

    profiles = Profile.objects.filter(
        hospital_name=request.user.username).order_by('name')
    patients = profiles.filter(user_type='patient')
    submissions = Submission.objects.filter(
        user__profile__hospital_name=request.user.username)

    counts = {
        'total': profiles.count() - 1,
        'patients': patients.count(),
        'status_updates': submissions.count(),
    }

    SUB_DISPLAY = 25
    sub_start = int(request.GET.get('start')) if 'start' in request.GET else 0
    sub_end = int(request.GET.get('end')
                  ) if 'end' in request.GET else SUB_DISPLAY
    sub_total = profiles.count()
    sub_pages = math.ceil(sub_total / SUB_DISPLAY)
    current_page = math.ceil(sub_end / SUB_DISPLAY)

    submissions = submissions.order_by('-date_added')[sub_start:sub_end]

    context = {
        'page': 'all_patients',
        'counts': counts,
        'patients': patients,
        'sub_start': sub_start + 1,
        'sub_end': sub_end if sub_end < sub_total else sub_total,
        'sub_pages': sub_pages,
        'sub_total': sub_total,
        'sub_range': range(1, sub_pages + 1),
        'current_page': current_page
    }
    return render(request, 'portal/patients_all.html', context)


@login_required
def all_doctors_view(request):

    profiles = Profile.objects.filter(
        hospital_name=request.user.username).order_by('name')
    patients = profiles.filter(user_type='patient')
    doctors = profiles.filter(user_type='doctor')

    counts = {
        'total': profiles.count() - 1,
        'patients': patients.count(),
        'doctors': doctors.count(),
    }

    SUB_DISPLAY = 10
    sub_start = int(request.GET.get('start')) if 'start' in request.GET else 0
    sub_end = int(request.GET.get('end')
                  ) if 'end' in request.GET else SUB_DISPLAY
    sub_total = profiles.count()
    sub_pages = math.ceil(sub_total / SUB_DISPLAY)
    current_page = math.ceil(sub_end / SUB_DISPLAY)

    context = {
        'page': 'all_doctors',
        'counts': counts,
        'doctors': doctors,

        'sub_start': sub_start + 1,
        'sub_end': sub_end if sub_end < sub_total else sub_total,
        'sub_pages': sub_pages,
        'sub_total': sub_total,
        'sub_range': range(1, sub_pages + 1),
        'current_page': current_page
    }
    return render(request, 'portal/doctors_all.html', context)


@login_required
def report_detail_view(request, pk):
    context = {
        'page': 'archive',
        'report': Submission.objects.get(pk=pk),
    }
    return render(request, 'portal/report_detail.html', context)


@login_required
def patient_detail_view(request, pk):
    context = {
        'page': 'all_patients',
        'profile': Profile.objects.get(pk=pk),
    }
    return render(request, 'portal/patient_detail.html', context)


@login_required
def doctor_detail_view(request, pk):
    context = {
        'page': 'all_doctors',
        'profile': Profile.objects.get(pk=pk),
    }
    return render(request, 'portal/doctor_detail.html', context)


@login_required
def patient_add_view(request):

    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)

        if user_form.is_valid():
            user = user_form.save()
            # profile = profile_form.save(commit=False)
            # for key in profile.keys():
            #     print(key)

            messages.add_message(
                request, messages.SUCCESS, f'Patient ID "{user.username}" registered successfully')

    user_form = UserCreationForm()
    # profile_form = PatientProfileForm()

    context = {
        'page': 'portal_actions',
        'user_form': user_form,
    }

    return render(request, 'portal/patient_add.html', context)


@login_required
def doctor_add_view(request):

    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        profile_form = DoctorProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            user.profile.user_type = 'doctor'
            user.profile.name = profile.name
            user.profile.phone_no = profile.phone_no
            user.profile.address = profile.address
            user.profile.province = profile.province
            user.profile.save()
            messages.add_message(
                request, messages.SUCCESS, f'Doctor "{profile.name}" registered successfully')

    user_form = UserCreationForm()
    profile_form = DoctorProfileForm()

    context = {
        'page': 'portal_actions',
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'portal/doctor_add.html', context)


@login_required
def assign_patient_view(request, pk):
    patient = Profile.objects.get(pk=pk)

    try:
        currently_assigned = patient.assigned_to.profile.name
    except:
        currently_assigned = 'None'

    if 'assigned_to' in request.GET.keys():
        form = AssignForm(request.GET)
        if form.is_valid():
            form = form.save(commit=False)

portal/templates/portal/base.html
{% load static %}

<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} | Upachar Portal</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
        rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'portal/css/tailwind.output.css' %}" />
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <script src="{% static 'portal/js/init-alpine.js' %}"></script>

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    {% block css %}{% endblock %}
</head>

<body>
    <div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen }">
        {% include 'portal/aside_bar.html' %}
        <div class="flex flex-col flex-1 w-full">
            {% include 'portal/header_bar.html' %}
            
            {% block content %}{% endblock %}
        </div>
    </div>
    {% block js %}{% endblock %}
</body>

</html>

portal/templates/portal/doctor_add.html
{% extends 'portal/base.html' %}

{% load tailwind_filters %}
{% load static %}
{% load custom_tags %}

{% block title %}
Patient Details
{% endblock %}

{% block css %}
<style>
    .upach-btn {
        border: 1px solid lightgreen;
        padding: 10px;
        border-radius: 32px;
    }

    .upach-btn:hover {
        background-color: lightgreen;
        transition: 0.420s;
    }
</style>
{% endblock %}

{% block content %}
<main class="h-full overflow-y-auto">
    <div class="container px-6 mx-auto grid">
        <h2 class="mt-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
            Add doctor:
        </h2>
        <div class="my-8 w-full overflow-hidden">
            <div class="text-gray-700 dark:text-gray-300">
                {% if messages %}
                {% for message in messages %}
                <div class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4" role="alert">
                    <p class="font-bold">Success!</p>
                    <p>{{ message }}</p>
                  </div>
                {% endfor %}
                {% endif %}
                <form action="" method="POST">{% csrf_token %}
                    {{ user_form|crispy }}
                    {{ profile_form|crispy }}
                    <button class="my-6 upach-btn">Create New</button>
                </form>

            </div>
        </div>
    </div>
</main>
{% endblock %}

portal/templates/portal/doctors_all.html
{% extends 'portal/base.html' %}

{% load static %}
{% load custom_tags %}

{% block title %}
Archived Reports
{% endblock %}

{% block content %}
<main class="h-full overflow-y-auto">
    <div class="container px-6 mx-auto grid">
        <h2 class="mt-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
            All Doctors
        </h2>
        <h3 class="my-6 text-sm font-semibold text-gray-700 dark:text-gray-200">
            Click on doctor name to view full doctor details
        </h3>

        <!-- New Table -->
        <div class="w-full overflow-hidden rounded-lg shadow-xs">
            <div class="w-full overflow-x-auto">
                <table class="w-full whitespace-no-wrap">
                    <thead>
                        <tr
                            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                            <th class="px-4 py-3">Doctor Name</th>
                            <th class="px-4 py-3">Assigned Patients</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                        {% for doctor in doctors %}
                        <tr class="text-gray-700 dark:text-gray-400">
                            <td class="px-4 py-3">
                                <span>
                                    <a href="{% url 'portal:doctor_detail' pk=doctor.pk%}">
                                        <span class="font-semibold">
                                            {{ doctor.name }}
                                        </span>
                                    </a>
                                </span>
                            </td>
                            <td class="px-4 py-3 text-sm">
                                {{ doctor.get_assigned_count }}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
{% endblock %}

portal/templates/portal/header_bar.html
<header class="z-10 py-4 bg-white shadow-md dark:bg-gray-800">
    <div
        class="container flex items-center justify-between h-full px-6 mx-auto text-purple-600 dark:text-purple-300">
        <!-- Mobile hamburger -->
        <button class="p-1 mr-5 -ml-1 rounded-md md:hidden focus:outline-none focus:shadow-outline-purple"
            @click="toggleSideMenu" aria-label="Menu">
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd"
                    d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                    clip-rule="evenodd"></path>
            </svg>
        </button>
        <!-- Search input -->
        <div class="flex justify-center flex-1 lg:mr-32">
            <div class="relative w-full max-w-xl mr-6 focus-within:text-purple-500">
                <div class="absolute inset-y-0 flex items-center pl-2">
                    <svg class="w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd"
                            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                            clip-rule="evenodd"></path>
                    </svg>
                </div>
                <input
                    class="w-full pl-8 pr-2 text-sm text-gray-700 placeholder-gray-600 bg-gray-100 border-0 rounded-md dark:placeholder-gray-500 dark:focus:shadow-outline-gray dark:focus:placeholder-gray-600 dark:bg-gray-700 dark:text-gray-200 focus:placeholder-gray-500 focus:bg-white focus:border-purple-300 focus:outline-none focus:shadow-outline-purple form-input"
                    type="text" placeholder="Search" aria-label="Search" />
            </div>
        </div>
        <ul class="flex items-center flex-shrink-0 space-x-6">
            <!-- Theme toggler -->
            <li class="flex">
                <button class="rounded-md focus:outline-none focus:shadow-outline-purple"
                    @click="toggleTheme" aria-label="Toggle color mode">
                    <template x-if="!dark">
                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                            <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z">
                            </path>
                        </svg>
                    </template>
                    <template x-if="dark">
                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd"
                                d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </template>
                </button>
            </li>
            <!-- Notifications menu -->
            <li class="relative">
                <button
                    class="relative align-middle rounded-md focus:outline-none focus:shadow-outline-purple"
                    @click="toggleNotificationsMenu" @keydown.escape="closeNotificationsMenu"
                    aria-label="Notifications" aria-haspopup="true">
                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z">
                        </path>
                    </svg>
                    <!-- Notification badge -->
                    <!-- <span aria-hidden="true"
                        class="absolute top-0 right-0 inline-block w-3 h-3 transform translate-x-1 -translate-y-1 bg-red-600 border-2 border-white rounded-full dark:border-gray-800"></span> -->
                </button>
                <template x-if="isNotificationsMenuOpen">
                    <ul x-transition:leave="transition ease-in duration-150"
                        x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0"
                        @click.away="closeNotificationsMenu" @keydown.escape="closeNotificationsMenu"
                        class="absolute right-0 w-56 p-2 mt-2 space-y-2 text-gray-600 bg-white border border-gray-100 rounded-md shadow-md dark:text-gray-300 dark:border-gray-700 dark:bg-gray-700">
                        <li class="flex">
                            <a class="inline-flex items-center justify-between w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                                href="#">
                                <span>Messages</span>
                                <span
                                    class="inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-green-600 bg-red-100 rounded-full dark:text-red-100 dark:bg-red-600">
                                    0
                                </span>
                            </a>
                        </li>
                    </ul>
                </template>
            </li>
            <!-- Profile menu -->
            <li class="relative">
                <button class="align-middle rounded-full focus:shadow-outline-purple focus:outline-none"
                    @click="toggleProfileMenu" @keydown.escape="closeProfileMenu" aria-label="Account"
                    aria-haspopup="true">
                    <!-- <img class="object-cover w-8 h-8 rounded-full" src="#" alt="hospital logo"
                        aria-hidden="true" /> -->
                        {{ request.user }}
                </button>
                <template x-if="isProfileMenuOpen">
                    <ul x-transition:leave="transition ease-in duration-150"
                        x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0"
                        @click.away="closeProfileMenu" @keydown.escape="closeProfileMenu"
                        class="absolute right-0 w-56 p-2 mt-2 space-y-2 text-gray-600 bg-white border border-gray-100 rounded-md shadow-md dark:border-gray-700 dark:text-gray-300 dark:bg-gray-700"
                        aria-label="submenu">
                        <li class="flex">
                            <a class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                                href="#">
                                <svg class="w-4 h-4 mr-3" aria-hidden="true" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    viewBox="0 0 24 24" stroke="currentColor">
                                    <path
                                        d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z">
                                    </path>
                                </svg>
                                <span>Profile</span>
                            </a>
                        </li>
                        <li class="flex">
                            <a class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                                href="#">
                                <svg class="w-4 h-4 mr-3" aria-hidden="true" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    viewBox="0 0 24 24" stroke="currentColor">
                                    <path
                                        d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z">
                                    </path>
                                    <path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                </svg>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li class="flex">
                            <a class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                                href="{% url 'portal:logout' %}">
                                <svg class="w-4 h-4 mr-3" aria-hidden="true" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    viewBox="0 0 24 24" stroke="currentColor">
                                    <path
                                        d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1">
                                    </path>
                                </svg>
                                <span>Log out</span>
                            </a>
                        </li>
                    </ul>
                </template>
            </li>
        </ul>
    </div>
</header>

portal/templates/portal/logout.html
{% extends 'portal/base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
<div style="display:flex; justify-content:center; align-items:center;">
    <div class="d-flex flex-column text-center my-5 text-gray-700 dark:text-gray-400">
        <br><br>
        <br><br>
        You have been logged out successfully.
        <br><br>
        Redirecting in <span id="counter">3</span>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">

    function countdown() {
        let countEl = document.getElementById('counter');
        if (parseInt(countEl.innerHTML) === 1) {
            location.href = '{% url "portal:login" %}';
        }
        if (parseInt(countEl.innerHTML) !== 1) {
            countEl.innerHTML = parseInt(countEl.innerHTML) - 1;
        }
    }
    setInterval(function () { countdown(); }, 1000);
</script>
{% endblock %}